query getSimulaltion(
  $items: [ShippingItem]
  $postalCode: String
  $country: String
) @context(provider: "vtex.store-graphql") {
  shipping(items: $items, postalCode: $postalCode, country: $country) {
    items {
      availability
    }
    logisticsInfo {
      selectedSla
      slas {
        name
        price
        shippingEstimate
        friendlyName
        pickupStoreInfo {
          friendlyName
          address {
            addressType
            receiverName
            addressId
            postalCode
            city
            state
            country
            street
            number
            neighborhood
            complement
            reference
            geoCoordinates
          }
        }
        deliveryIds {
          courierName
          quantity
        }
      }
    }
  }
}
